version: '3.8'

services:
  app:
    image: 'docker-spring-boot-postgres:latest'
    build:
      context: .
    container_name: app
    networks:
      - my-network-name
    depends_on:
      - db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/talkiaTPDB
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

    ports:
      - "6868:8080"
  db:
    image: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    restart: always
    container_name: db
    networks:
      - my-network-name
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=talkiaTPDB
    ports:
      - "5433:5432"
volumes:
  db_data:
networks:
  my-network-name:
    name: TalkiaCloud